### ISSUE TITLE
No Ping Response on kown IPs

### ISSUE THREAD

**Issue by Beufff** [pluginsGLPI/addressing#76]
Hello everyone,
I recently installed the "IP Addressing" plugin on my GLPI in docker (dioux image) via marketplace.
When I configure an IP range in the plugin, the report shows the IPs of the machines in the inventory, but it does not give a ping response. I get a "Ping: no response - free IP" result on all the range. This leads me to believe that the plugin is unable to ping my local network. Have I missed a network configuration in docker? I just have a bridge network between GLPI and Mariadb. 
Do I need to install ping install the container?
I can ping from my Ubuntu host.

Thanks in advance for your help! 

Setup : 

- GLPI 10.0.12
- Plugin version : 3.0.2
- Docker compose : 
```
version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - /home/administrator/docker/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=xxx
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=xxx
    restart: always
#GLPI Container
  glpi:
    image: diouxx/glpi:latest
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/administrator/docker/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Brussels
    restart: always
```
